
OGL_CFG_BOOL(FogEnable,                true, "")
OGL_CFG_BOOL(InitFullScreen,           true, "")
OGL_CFG_BOOL(PrecisionFix,             true, "")
OGL_CFG_INT(CreateWindow,             1, 0, 2, "Create Window if NULL is passed to grSstWinOpen")
OGL_CFG_BOOL(EnableMipMaps,            true, "")
OGL_CFG_BOOL(BuildMipMaps,            false, "")
OGL_CFG_BOOL(IgnorePaletteChange,     false, "")
OGL_CFG_BOOL(ARB_multitexture,         true, "")
OGL_CFG_BOOL(EXT_paletted_texture,     true, "")
OGL_CFG_BOOL(EXT_texture_env_add,     false, "")
OGL_CFG_BOOL(EXT_texture_env_combine, false, "")
OGL_CFG_BOOL(EXT_vertex_array,        false, "")
OGL_CFG_BOOL(EXT_fog_coord,            true, "")
OGL_CFG_BOOL(EXT_blend_func_separate, false, "")
OGL_CFG_BOOL(Wrap565to5551,            true, "")
OGL_CFG_BOOL(MMXEnable,                true, "")

OGL_CFG_FLOAT(Resolution,          0,   0,   16, "Scale screen, 0 = 1 = disabled, 2 = 2x scale (800x600 => 1600x1200)")
OGL_CFG_INT(TextureMemorySize,     8,   2,   32, "Texture memory size in MB, from 2 to 32")
OGL_CFG_INT(FrameBufferMemorySize, 8,   2,   16, "Frame buffer size in MB, from 2 to 16")
OGL_CFG_INT(Priority,              2,   0,    5, "0 = highest, 5 = lowest")
OGL_CFG_INT(HideCursor,            1,   0,    2, "Try to suppress flashing cursor, 0 = disable, 1 = hide by thread, 2 = disable is whole system, when GLIDE active")
OGL_CFG_BOOL(NoSplash,                     true, "Disable 3DFX splash screen")
OGL_CFG_BOOL(ShamelessPlug,               false, "")
OGL_CFG_BOOL(Logging,                     false, "")

OGL_CFG_INT(NumTMU,                1,   1,    GLIDE_NUM_TMU, "Number of texture mapping units (TMU), 1 = most compatible")
OGL_CFG_INT(SSTType,              -1,  -1,    4, "Type of Voodoo board: -1 = auto, 0 = Voodoo, 1 = Rush, 3 = Voodoo2, 4 = Banshee")
