#ifndef __OPENGLIDE9X_VERSION_H__INCLUDED__

#define OPENGLIDE9X_STR_(x) #x
#define OPENGLIDE9X_STR(x) OPENGLIDE9X_STR_(x)

#define OPENGLIDE9X_MAJOR 0
#define OPENGLIDE9X_MINOR 1
#define OPENGLIDE9X_PATCH 2024

#ifndef OPENGLIDE9X_BUILD
#define OPENGLIDE9X_BUILD 0
#endif

#define OPENGLIDE9X_VERSION_STR_BUILD(_ma, _mi, _pa, _bl) \
	_ma "." _mi "." _pa "." _bl

#define OPENGLIDE9X_VERSION_STR OPENGLIDE9X_VERSION_STR_BUILD( \
	OPENGLIDE9X_STR(OPENGLIDE9X_MAJOR), \
	OPENGLIDE9X_STR(OPENGLIDE9X_MINOR), \
	OPENGLIDE9X_STR(OPENGLIDE9X_PATCH), \
	OPENGLIDE9X_STR(OPENGLIDE9X_BUILD))

#define OPENGLIDE9X_VERSION_NUM \
 	OPENGLIDE9X_MAJOR,OPENGLIDE9X_MINOR,OPENGLIDE9X_PATCH,OPENGLIDE9X_BUILD \

#define CURSOR_TRANSPARENT 127

#endif /* __OPENGLIDE9X_VERSION_H__INCLUDED__ */
